middlewares:
  handlers:
    default:
      filter: # By default, middleware will be plugged on every actions.
        #routeName: "*"
        #routePath: "*"
        controller: ~ # Should be the class name / service name?
      collection: # should be the collection class name / service name
      #priority: 1
