services:
  _defaults:
    autowire: true
    autoconfigure: true

  NoGlitchYo\MiddlewareBundle\:
    resource: '../../*'
    exclude: '../{DependencyInjection,Entity,Migrations,Tests,Kernel.php,HttpKernel}'

  NoGlitchYo\MiddlewareBundle\Middleware\Stack\MiddlewareStackInterface: '@middlewares.stack'
  NoGlitchYo\MiddlewareBundle\Middleware\Matcher\RequestMatcher: ~

  middlewares.stack:
    class: NoGlitchYo\MiddlewareBundle\Middleware\Stack\MiddlewareStack
    configurator: '@NoGlitchYo\MiddlewareBundle\MiddlewareStackConfigurator'
    arguments:
      $matcher: '@NoGlitchYo\MiddlewareBundle\Middleware\Matcher\RequestMatcher'

  NoGlitchYo\MiddlewareBundle\MiddlewareStackConfigurator:
    arguments:
      $handlers: !tagged middlewares.handler_configuration

